"""rename fields in courses table

Revision ID: 0ef201a0c28c
Revises: e195ba6b081c
Create Date: 2024-03-16 03:01:30.582669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0ef201a0c28c'
down_revision: Union[str, None] = 'e195ba6b081c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'course_id', new_column_name='id',
                    type_=sa.Integer, nullable=False)
    op.alter_column('courses', 'course_name',
                    new_column_name='name', type_=sa.String(20), nullable=True)
    op.alter_column('courses', 'course_description',
                    new_column_name='description', type_=sa.String(256), nullable=True)
    op.alter_column('courses', 'course_start_date',
                    new_column_name='start_date', type_=sa.Date, nullable=True)
    op.alter_column('courses', 'course_end_date',
                    new_column_name='end_date', type_=sa.Date, nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'id', new_column_name='course_id',
                    type_=sa.Integer, nullable=False)
    op.alter_column('courses', 'name', new_column_name='course_name',
                    type_=sa.String(20), nullable=True)
    op.alter_column('courses', 'description', new_column_name='course_description',
                    type_=sa.String(256), nullable=True)
    op.alter_column('courses', 'start_date',
                    new_column_name='course_start_date', type_=sa.Date, nullable=True)
    op.alter_column('courses', 'end_date',
                    new_column_name='course_end_date', type_=sa.Date, nullable=True)
    # ### end Alembic commands ###
