"""Rename columns in students table

Revision ID: 2300afe0c92a
Revises: 
Create Date: 2024-03-16 00:55:23.344714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2300afe0c92a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'student_id', new_column_name='id',type_=sa.String(length=50), nullable=False)
    op.alter_column('students', 'student_pw', new_column_name='pw',type_=sa.String(length=50))
    op.alter_column('students', 'student_name', new_column_name='name',type_=sa.String(length=20))
    op.alter_column('students', 'student_contact', new_column_name='contact',type_=sa.String(length=20))
    op.alter_column('students', 'student_email', new_column_name='email',type_=sa.String(length=50))
    op.alter_column('students', 'student_birth_date', new_column_name='birth_date',type_=sa.Date())
    op.alter_column('students', 'student_gender', new_column_name='gender',type_=sa.String(length=10))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'id', new_column_name='student_id',type_=sa.String(length=50), nullable=False)
    op.alter_column('students', 'pw', new_column_name='student_pw',type_=sa.String(length=50))
    op.alter_column('students', 'name', new_column_name='student_name',type_=sa.String(length=20))
    op.alter_column('students', 'contact', new_column_name='student_contact',type_=sa.String(length=20))
    op.alter_column('students', 'email', new_column_name='student_email',type_=sa.String(length=50))
    op.alter_column('students', 'birth_date', new_column_name='student_birth_date',type_=sa.Date())
    op.alter_column('students', 'gender', new_column_name='student_gender',type_=sa.String(length=5))
    # ### end Alembic commands ###
