"""create cost(int) column in courses table.

Revision ID: ab6c0a58f4fe
Revises: 48c325e9459c
Create Date: 2024-04-17 12:31:46.732008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ab6c0a58f4fe'
down_revision: Union[str, None] = '48c325e9459c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column(
        'cost', sa.Integer, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'cost')
    # ### end Alembic commands ###
